#!/usr/bin/env bash
# Project setup for the Champions League Match Intelligence Data Platform.
#
# Creates an isolated virtualenv in .venv, installs the package and prepares .env.
# Uses only the Python standard library's venv module on purpose: a peer reviewer
# must be able to run this on a plain machine without pyenv, direnv or conda.
# Override the interpreter with:  PYTHON=python3.12 ./setup.sh

# Fail fast: -e stops at the first failing command, -u treats an unset
# variable as an error (instead of an empty string), and -o pipefail makes a
# pipeline fail if any part of it fails - not only the last command.
set -euo pipefail

MIN_VERSION="3.10"

echo "Setting up the Champions League Match Intelligence Data Platform"
echo

# --- 1. Find a suitable interpreter ----------------------------------------
PYTHON="${PYTHON:-}"
if [ -z "$PYTHON" ]; then
    # The candidate must satisfy the version floor AND be able to build a venv.
    # `import venv` alone is not enough: Debian/Ubuntu ship python3.12 without
    # the python3.12-venv package, where venv imports fine and creation then
    # fails with "ensurepip is not available".
    for candidate in python3.13 python3.12 python3.11 python3.10 python3; do
        if command -v "$candidate" >/dev/null 2>&1 &&
            "$candidate" -c \
                'import sys, venv, ensurepip; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' \
                2>/dev/null; then
            PYTHON="$candidate"
            break
        fi
    done
fi

if [ -z "$PYTHON" ]; then
    echo "ERROR: no Python >= $MIN_VERSION that can create a virtualenv was found."
    echo "  Interpreters on PATH:"
    for candidate in python3.13 python3.12 python3.11 python3.10 python3; do
        if command -v "$candidate" >/dev/null 2>&1; then
            note=$("$candidate" -c 'import venv, ensurepip' 2>/dev/null \
                   || echo "  <- venv/ensurepip missing")
            echo "    $candidate $("$candidate" --version 2>&1 | cut -d' ' -f2)$note"
        fi
    done
    echo "  Debian/Ubuntu/WSL: sudo apt install python3-venv   (or python3.12-venv)"
    echo "  Have one already?  PYTHON=/path/to/python3.12 ./setup.sh"
    exit 1
fi
echo "Interpreter: $PYTHON ($("$PYTHON" --version 2>&1))"

# --- 2. Virtualenv ----------------------------------------------------------
if [ -x .venv/bin/python ] &&
    ! .venv/bin/python -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' \
        2>/dev/null; then
    echo "Existing .venv uses an unsupported Python - recreating it."
    rm -rf .venv
fi

echo "Creating virtualenv in .venv"
"$PYTHON" -m venv .venv

# --- 3. Dependencies --------------------------------------------------------
echo "Installing the package and its dev dependencies"
.venv/bin/pip install --quiet --upgrade pip
.venv/bin/pip install --quiet -e ".[dev]"

# --- 4. Configuration -------------------------------------------------------
if [ ! -f .env ]; then
    cp .env.example .env
    echo "Created .env from .env.example"
fi

# --- 5. Optional: direnv auto-activation ------------------------------------
# Only for reviewers who happen to use direnv; never required. .envrc is
# git-ignored on purpose (it commonly holds secrets in other projects), so it
# is generated here instead of being committed.
if command -v direnv >/dev/null 2>&1 && [ ! -f .envrc ]; then
    cat >.envrc <<'ENVRC'
# Generated by setup.sh - activates .venv when you cd into the project.
export VIRTUAL_ENV="$PWD/.venv"
PATH_add "$VIRTUAL_ENV/bin"
ENVRC
    direnv allow . && echo "direnv enabled - the venv activates automatically in this folder"
fi

# --- 6. Verify --------------------------------------------------------------
echo
if [ -f scripts/doctor.py ]; then
    .venv/bin/python scripts/doctor.py || true
else
    .venv/bin/python -c "import deng; print('package deng importable:', deng.__version__)"
fi

cat <<'MESSAGE'

Next steps:
  1. add your free API key to .env   (https://www.football-data.org/client/register)
  2. make test      run the unit tests
  3. make explore   fetch real sample payloads

Activating the virtualenv is optional - every make target uses .venv directly.
To work interactively:  source .venv/bin/activate
MESSAGE
